dist: bionic
language: php
php:
  - 7.3
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - $HOME/.cache/pip
before_install:
  - docker pull nextdom/nextdom-test:latest
  - mkdir -p tests/coverage
  - composer require --dev symfony/panther:0.6.0 symfony/css-selector
  - wget -q -O phpunit https://phar.phpunit.de/phpunit-7.phar && chmod +x phpunit
  - docker run -d --rm -p 8765:80 -v `pwd`:/data --name="nextdom-test" nextdom/nextdom-test:latest bash -x /start.sh
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends python3-pip python3-setuptools dpkg ruby-sass
  - sudo python -m pip install --upgrade pip jsmin
  - sudo python3 -m pip install --upgrade pip jsmin
  - python3 -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)" # Fix travis error
  - sudo pip3 install --ignore-installed urllib3[secure] pylint
  - ./scripts/gen_global.sh
  - composer require --dev php-coveralls/php-coveralls
  - while true; do DOCKER_LOGS=$(docker logs --tail 10 nextdom-test 2>&1); if [[ "$DOCKER_LOGS" =~ .*NEXTDOM.TEST.READY.* ]]; then break; fi; sleep 2; done
  - docker commit nextdom-test nextdom-test-snap
  - docker kill nextdom-test
script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - python3 launch_php_tests.py
  - cat coverage/junitlog.xml | nc termbin.com 9999
  - python3 send_timestamps.py | nc termbin.com 9999
  - python3 launch_code_consistency.py
  - python3 launch_compatibility_tests.py
after_script:
  - cat tests/coverage/junitlog.xml
  - cd ${TRAVIS_BUILD_DIR}
  - sed -i "s/\/usr\/share\/nextdom\///g" tests/coverage/clover.xml
  - php vendor/bin/php-coveralls -v
  - ./scripts/push_doc.sh
env:
  global:
    secure: XH1F7R5rvX8CLj8kT63ye3YwMiSM3YYN2rL6E4u1jM9/UZ7MB3GLtNzoarXe0jr/6C0Ugh+hhkolhaaOAzqNFft2QzyOfBcOElpzjyVhl0BZtEDANd2xFJZi3hfHpULptzbGiNxwmaB2PYxD+6eVcMwXXOfE1k1zpqiFdjmhZzsE4s6rC6SIDIV06ySp4bWzJpbv+JYitZbmA9Sm7UQCoTAUtX0iKS66h94Anlyg6GUka2iPBP93rZu31D2TEAxyHTuFJzNHfdx8lcisAdSaxbRb/4qYsmKJzG63OUX6qoCYZBkZWcyMOZGVNhFaa1kaixkTULc3SNYcR3C7U8VekYUV5hppDBk7OoJ8+mG4EQvl1yy4xZueMQhfuCyUKXkqDKJRP8PciB9Mpu/qD7Yj9HxNpMYnurx40aVZZ2aAIPebYGSdbDg4416+A28eO2wVWMPOdllyFgil8rQnHZ8IFRSoCu0SWIpd2TTYoiuXgHmMonpyp8Yw/vw+E5I5FeXD59viRU4xREv+tcS0BHJ1ncTX0Dwegs7dSVxspwftwAeWaI489JiWDMUDgayqUH4y3bgW8iYFvharckKiUbaKg+U0v8IuWlqpKjE38StNiarzMs+xzAY2IIiWJxIEGQ1pXxXI8JNJrH6RSNik+px/z066YZgTbTQBhe4K45azJ/Y=
