language: php
php:
    - 7.1
services:
    - docker
addons:
    chrome: stable
before_install:
    - docker pull nextdom/nextdom-core:test
    - mkdir -p tests/coverage
    - docker run -d --rm -p 8765:80 -v `pwd`:/data --name="nextdom-test" nextdom/nextdom-core:test
    - sudo apt update
    - sudo apt install -y python3-pip python-pip
    - sudo python3 -m pip install --upgrade pip
    - sudo pip3 install --ignore-installed urllib3[secure] pylint
    - sudo pip install jsmin
    - ./scripts/gen_global.sh
    - composer install --dev
    - composer require --dev satooshi/php-coveralls
    - "while true; do DOCKER_LOGS=$(docker logs --tail 10 nextdom-test 2>&1); if [[ \"$DOCKER_LOGS\" =~ .*NEXTDOM.TEST.READY.* ]]; then break; fi; sleep 2; done"
    - docker exec -it nextdom-test bash -c "cd /var/www/html && composer install --dev"
    - docker commit nextdom-test nextdom-test-snap
    - docker kill nextdom-test
    - cd tests
    - sudo ./install_env.sh
script:
    - cd ${TRAVIS_BUILD_DIR}/tests
    - python3 launch_php_tests.py
    - python3 check_jeedom_compatibility_from_src.py
    - python3 launch_compatibility_tests.py
    - python3 launch_code_consistency.py
    - python3 launch_features_tests.py
    - python3 launch_gui_tests.py
after_script:
    - cd ${TRAVIS_BUILD_DIR}
    - sed -i "s/\/var\/www\/html/\/home\/travis\/build\/NextDom\/nextdom-core/g" tests/coverage/clover.xml
    - php vendor/bin/php-coveralls -v
