dist: trusty
language: php
php:
    - 7.3
services:
    - docker
#addons:
#    sonarcloud:
#        organization: "nextdom"
#        token:
#            secure: GtxUlb7OHChNapdoSpicL5YFLzNLXF7qEjRLk+mjYb7UF8drSSj67L6pxohbCl01kbG8OtEazzplzsnNpbrHhyAwfyuKtP8NYOOcC6nMptDUF9Fx1i45vM7Vom+pPnzPRxztLqZfZ2e1Ua9XrEFybZ7aiAN+KufYSrXwjoI6Ngt7xY76lbbwj4O+2mdR4OCR5YoC6NbdeOBclWTF2fER9bda1rAOTeNkht/+ZRvrPWVv43ELzXUAHFz4A9nqIx+v4ho+9Gy1qpv7B7OUQPlNqkHZL1UWgZ48XZ8Cz8boBrce9mPsHcxjXyB+hfMfbljNbweEMERTilz0q2pT30Cn2WBRaf+/BMau2LHaUxMS26pp4V5dvVIlmAW4nJbYOT2FFTG0HXAxMuRvzCC+3PdUHK08/BUET6NNitnCwf2+E+Zwva53wautdpgfC9sk+G+DbevkXAcQoOfhHXR8jMFBurZEsXEkpiQLpgplT7YS5iOtpq50eaBH6CYH0mutFB7z4tEV4/3V7WN02aJ/5HJY5lrXx4eMoI+AHp69iVmGdT27fWG7GvbOh+Mb2yYSJAQANSH3DnAV0rA/sFLTW1wmht8P9/Ms+lprIytzj1dBdcKwyUBUtGgtx3HZBJqL+P9YfQaFWNZJrvr0W2TeN4PPtnc7MwXPsoK3vGk5GygJMTE=
before_install:
    - docker pull nextdom/nextdom-test:latest
    - mkdir -p tests/coverage
    - docker run -d --rm -p 8765:80 -v `pwd`:/data --name="nextdom-test" nextdom/nextdom-test:latest /start.sh
    - sudo apt update
    - sudo apt install -y python3-pip python-pip python3-setuptools dpkg
    - sudo python -m pip install --upgrade pip jsmin
    - sudo python3 -m pip install --upgrade pip jsmin
    - sudo pip3 install --ignore-installed urllib3[secure] pylint
    - export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
    - wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
    - sudo dpkg -i /tmp/$(basename $CHROME_SOURCE_URL)
    - ./scripts/gen_global.sh
    - composer require --dev satooshi/php-coveralls
    - composer install --dev
    - "while true; do DOCKER_LOGS=$(docker logs --tail 10 nextdom-test 2>&1); if [[ \"$DOCKER_LOGS\" =~ .*NEXTDOM.TEST.READY.* ]]; then break; fi; sleep 2; done"
    - docker exec -it nextdom-test bash -c "cd /var/www/html && composer install --dev"
    - docker commit nextdom-test nextdom-test-snap
    - docker kill nextdom-test
    - cd tests
    - sudo ./install_env.sh
script:
    - cd ${TRAVIS_BUILD_DIR}/tests
    - python3 launch_php_tests.py
    - python3 check_jeedom_compatibility_from_src.py
    - python3 launch_compatibility_tests.py
    - python3 launch_code_consistency.py
    - python3 launch_features_tests.py
    - python3 launch_gui_tests.py
after_script:
    - cd ${TRAVIS_BUILD_DIR}
    - ls tests/coverage/
    - sed -i "s/\/usr\/share\/nextdom\///g" tests/coverage/clover.xml
    - php vendor/bin/php-coveralls -v
#    - sonar-scanner -X
#env:
#    global:
#        secure: GtxUlb7OHChNapdoSpicL5YFLzNLXF7qEjRLk+mjYb7UF8drSSj67L6pxohbCl01kbG8OtEazzplzsnNpbrHhyAwfyuKtP8NYOOcC6nMptDUF9Fx1i45vM7Vom+pPnzPRxztLqZfZ2e1Ua9XrEFybZ7aiAN+KufYSrXwjoI6Ngt7xY76lbbwj4O+2mdR4OCR5YoC6NbdeOBclWTF2fER9bda1rAOTeNkht/+ZRvrPWVv43ELzXUAHFz4A9nqIx+v4ho+9Gy1qpv7B7OUQPlNqkHZL1UWgZ48XZ8Cz8boBrce9mPsHcxjXyB+hfMfbljNbweEMERTilz0q2pT30Cn2WBRaf+/BMau2LHaUxMS26pp4V5dvVIlmAW4nJbYOT2FFTG0HXAxMuRvzCC+3PdUHK08/BUET6NNitnCwf2+E+Zwva53wautdpgfC9sk+G+DbevkXAcQoOfhHXR8jMFBurZEsXEkpiQLpgplT7YS5iOtpq50eaBH6CYH0mutFB7z4tEV4/3V7WN02aJ/5HJY5lrXx4eMoI+AHp69iVmGdT27fWG7GvbOh+Mb2yYSJAQANSH3DnAV0rA/sFLTW1wmht8P9/Ms+lprIytzj1dBdcKwyUBUtGgtx3HZBJqL+P9YfQaFWNZJrvr0W2TeN4PPtnc7MwXPsoK3vGk5GygJMTE=
