version: '3'
services:
 nextdom-mysql:
  container_name: ${MYSQLNAME}
  image: ${IMAGESQL}
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQLROOT}
    - MYSQL_ROOT_HOST=%
    - MYSQL_DATABASE=nextdom
    - MYSQL_USER=nextdom
    - MYSQL_HOST=${MYSQLHOST}
    - MYSQL_PASSWORD=${MYSQLROOT}
    - TZ= ${TZ}
  restart: ${RESTARTSQL}
  expose:
    - "3306"
  ports:
    - "${MYSQLMAP}"
 nextdom-dev:
  container_name: ${CNAME}
  #image: ${IMAGE}
  build:
    dockerfile: Dockerfile.develop
    context: .
  restart: ${RESTART}
  healthcheck:
    test: ["CMD","curl","-f","http://localhost/here.html"]
    interval: 10s
    timeout: 10s
  expose:
    - "22"
    - "80"
    - "443"
  ports:
    - "${HTTPMAP}"
    - "${HTTPSMAP}"
    - "${SSHMAP}"
  env_file: ./devAbeille.env
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQLROOT}
    - ROOT_PASSWORD=${ROOT_PASSWORD}
    - MYSQL_DATABASE=nextdom
    - MYSQL_USER=nextdom
    - MYSQL_HOST=${MYSQLHOST}
    - MYSQL_PASSWORD=${MYSQLROOT}
    - VERSION=${VERSION}
    - TZ=${TZ}
  volumes:
    - ${PLUGINABEILLE}:/var/www/html/plugins/Abeille/:rw
  devices:
    #zigate
    - ${DUSB}
    #zwave
    #- ${DACM}
    #- ${DAMA}
  links:
   - nextdom-mysql:mysql
  depends_on:
   - nextdom-mysql
  stdin_open: true
  tty: true
