administration:
  path: 'administration'
  controller: NextDom\Controller\Pages\AdministrationController::get
  condition: 'admin'
api:
  path: 'api'
  controller: NextDom\Controller\Admin\ApiController::get
  condition: 'admin'
backup:
  path: 'backup'
  controller: NextDom\Controller\Tools\BackupController::get
  condition: 'admin'
cache:
  path: 'cache'
  controller: NextDom\Controller\Admin\CacheController::get
  condition: 'admin'
commandes:
  path: 'commandes'
  controller: NextDom\Controller\Params\CommandeController::get
  condition: 'admin'
connection:
  path: 'connection'
  controller: NextDom\Controller\Pages\ConnectionController::get
  condition: ''
cron:
  path: 'cron'
  controller: NextDom\Controller\Diagnostic\CronController::get
  condition: 'admin'
dashboard:
  path: 'dashboard'
  controller: NextDom\Controller\Pages\DashBoardController::get
  condition: 'user'
database:
  path: 'database'
  controller: NextDom\Controller\Tools\Osdb\DatabaseController::get
  condition: 'admin'
display:
  path: 'display'
  controller: NextDom\Controller\Tools\DisplayController::get
  condition: 'admin'
eqAnalyse:
  path: 'eqAnalyse'
  controller: NextDom\Controller\Diagnostic\EqAnalyzeController::get
  condition: 'admin'
eqlogic:
  path: 'eqlogic'
  controller: NextDom\Controller\Params\EqlogicController::get
  condition: 'admin'
firstUse:
  path: 'firstUse'
  controller: NextDom\Controller\Pages\FirstUseController::get
  condition: ''
general:
  path: 'general'
  controller: NextDom\Controller\Params\GeneralController::get
  condition: 'admin'
health:
  path: 'health'
  controller: NextDom\Controller\Diagnostic\HealthController::get
  condition: 'admin'
history:
  path: 'history'
  controller: NextDom\Controller\Diagnostic\HistoryController::get
  condition: 'user'
interact:
  path: 'interact'
  controller: NextDom\Controller\Tools\InteractController::get
  condition: 'admin'
interact_config:
  path: 'interact_config'
  controller: NextDom\Controller\Params\InteractConfigController::get
  condition: 'admin'
links:
  path: 'links'
  controller: NextDom\Controller\Params\LinksController::get
  condition: 'admin'
log:
  path: 'log'
  controller: NextDom\Controller\Diagnostic\LogController::get
  condition: 'admin'
log_config:
  path: 'log_config'
  controller: NextDom\Controller\Params\LogConfigController::get
  condition: 'admin'
market:
  path: 'market'
  controller: NextDom\Controller\Tools\Markets\MarketController::get
marketJee:
  path: 'marketJee'
  controller: NextDom\Controller\Tools\Markets\MarketJeeController::get
  condition: 'admin'
network:
  path: 'network'
  controller: NextDom\Controller\Admin\NetworkController::get
  condition: 'admin'
note:
  path: 'note'
  controller: NextDom\Controller\Tools\NoteController::get
  condition: 'admin'
object:
  path: 'object'
  controller: NextDom\Controller\Tools\ObjectController::get
  condition: 'admin'
osdb:
  path: 'osdb'
  controller: NextDom\Controller\Tools\OsDbController::get
  condition: 'admin'
panel:
  path: 'panel'
  controller: NextDom\Controller\Pages\PanelPageController::get
  condition: 'admin'
plan:
  path: 'plan'
  controller: NextDom\Controller\Pages\PlanController::get
  condition: 'user'
plan3d:
  path: 'plan3d'
  controller: NextDom\Controller\Pages\Plan3DController::get
  condition: 'user'
plugin:
  path: 'plugin'
  controller: NextDom\Controller\Tools\PluginListController::get
  condition: 'admin'
profils:
  path: 'profils'
  controller: NextDom\Controller\Params\ProfilsController::get
  condition: 'admin'
reboot:
  path: 'reboot'
  controller: NextDom\Controller\RebootController::get
  condition: 'admin'
report:
  path: 'report'
  controller: NextDom\Controller\Diagnostic\ReportController::get
  condition: 'admin'
report_config:
  path: 'report_config'
  controller: NextDom\Controller\Params\ReportConfigController::get
  condition: 'admin'
scenario:
  path: 'scenario'
  controller: NextDom\Controller\Tools\ScenarioController::get
  condition: 'admin'
security:
  path: 'security'
  controller: NextDom\Controller\Admin\SecurityController::get
  condition: 'admin'
services:
  path: 'services'
  controller: NextDom\Controller\Admin\ServicesController::get
  condition: 'admin'
shutdown:
  path: 'shutdown'
  controller: NextDom\Controller\ShutdownController::get
  condition: 'admin'
summary:
  path: 'summary'
  controller: NextDom\Controller\Params\SummaryController::get
  condition: 'user'
system:
  path: 'system'
  controller: NextDom\Controller\Tools\Osdb\SystemController::get
  condition: 'admin'
timeline:
  path: 'timeline'
  controller: NextDom\Controller\Diagnostic\TimelineController::get
  condition: 'admin'
update:
  path: 'update'
  controller: NextDom\Controller\Tools\UpdateController::get
  condition: 'admin'
users:
  path: 'users'
  controller: NextDom\Controller\Admin\UsersController::get
  condition: 'admin'
view:
  path: 'view'
  controller: NextDom\Controller\Pages\ViewController::get
  condition: 'user'
view_edit:
  path: 'view_edit'
  controller: NextDom\Controller\Pages\ViewEditController::get
  condition: 'admin'
